name = str(input("이름을 입력하세요: "))
studentID = int(input("학번을 입력하세요: "))
major = str(input("학과를 입력하세요: "))
univ = str(input("대학교를 입력하세요: "))

print("<출력>")
print("이름: ",name)
print("학번: ",studentID)
print("대학교: ",univ)
print("학과: ",major)
